### ISSUE TITLE
Number of nodes doesn't count those in subgraphs

### ISSUE THREAD

**Issue by james-d-mitchell** [digraphs/graphviz#15]
For example, in the rewrite of the graphviz stuff in Semigroups, I get the following:

~~~
gap> S := UniformBlockBijectionMonoid(5);
<inverse block bijection monoid of degree 5 with 3 generators>
gap> GraphvizSemilatticeOfIdempotents(S);
<graphviz graph semilattice with 0 nodes and 160 edges>
~~~

**Comment by mpan322** [comment]
Added a fix for node numbers to my fork of the graphviz will merge it in once I do the equivalent fix for edges as well tomorrow.
